---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 700513318868418560-H0KNinIsRiQy0NNa4aRLV6s6H6gxqMK
:access_token_secret: qolFaIgHzHUxESJjzkcupsnCXluOH7eR3Et4QWzLKvrOi
